<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inventario</title>
    <style>
        body {
            font-family: Monospace, sans-serif;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th,
        td {
            border: 1px solid #999;
            padding: 2px;
        }

        th {
            background-color: #f2f2f2;
        }

        .title {
            font-size: 24px;
            font-weight: bold;
            text-align: center;
        }

        .header-table {
            width: 100%;
            margin-bottom: 20px;
        }

        .header-table h1 {
            font-size: 16px;
            font-weight: bold;
            color: #333;
            text-align: center;
        }

        .text-red {
            color: red;
        }

        .text-yellow {
            color: orange;
        }
    </style>
</head>

<body class="bg-gray-100 font-sans">
    <div class="container mx-auto py-8">
        <table class="header-table">
            <tr>
                <td class="title" colspan="4">Reporte de Inventario</td>
            </tr>
            <tr>
                <td>
                    <h1>Generado por</h1>
                </td>
                <td> {{ auth()->user()->name . ' <' . auth()->user()->email . '>' }}</td>
                <td>
                    <h1>Fecha</h1>
                </td>
                <td>{{ now() }}</td>
            </tr>
        </table>
        <div class="overflow-x-auto">
            <table class="table-auto w-full">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Marca</th>
                        <th>Costo</th>
                        <th>Precio</th>
                        <th>Stock</th>
                        <th>Observ.</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($items as $item)
                        <tr>
                            <td class="border">{{ $item->id }}</td>
                            <td class="border">{{ $item->name }}</td>
                            <td class="border">{{ $item->brand }}</td>
                            <td class="border">{{ $item->cost }}</td>
                            <td class="border">{{ $item->price }}</td>
                            @if ($item->stock == 0)
                                <td class="border text-red">{{ $item->stock }}</td>
                            @elseif ($item->stock < 10)
                                <td class="border text-yellow">{{ $item->stock }}</td>
                            @else
                                <td class="border">{{ $item->stock }}</td>
                            @endif
                            <td class="border"></td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <footer>
        <div class="text-left">
            <p>Generated by Stocker v0.0.1</p>
        </div>
    </footer>
</body>

</html>
